### ISSUE TITLE
Manual and R function documentation do not match 

### ISSUE THREAD

**Issue by pcantalupo** [ZxZhou4150/Redeconve#9]
Hello, Just a minor issue about documentation

In the manual you say that the default for exp_thresh is 0.003 (`exp_thresh considers expression in spatial transcriptomics. ... The default value is 0.003.`) but the function documentation in R shows that exp_thresh default is 0.03:

```
Usage
deconvoluting(
  ref,
  st,
  cellnames = NULL,
  genemode,
  gene.list,
  var_thresh = 0.025,
  exp_thresh = 0.03,
```

**Comment by ZxZhou4150** [comment]
Hi,

This issue was pointed out in #6 and should have been fixed. The default value should be 0.003. I tried `?deconvoluting` and it is 0.003. Could you please provide more information about where it still displays as 0.03?

Thanks,
Zixiang

**Comment by pcantalupo** [comment]
I just installed the latest version and it is correctly set at 0.003.  Sorry about wasting your time.
